### ISSUE TITLE
Can you make the Pytorch and ONNX compatible with ChaiNNer

### ISSUE THREAD

**Issue by AlecMcCutcheon** [clibdev/colorization#1]
Like most of these models are: https://openmodeldb.info/

ChaiNNer: https://github.com/chaiNNer-org/chaiNNer

Also if possible can you make them NCNN compatible or release an NCNN version for gpu support.

**Comment by clibdev** [comment]
This repository currently handles only PyTorch and ONNX models. No plans to support NCNN.
